<%@ Page Language="C#" AutoEventWireup="true" CodeFile="MenuTree.aspx.cs" Inherits="Admin_MenuTree" %>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>导航菜单</title>
    <link href="Style/Main.css" rel="stylesheet" type="text/css" />
   <style>
   BODY
{
    SCROLLBAR-FACE-COLOR: #dfedf2;
    FONT-SIZE: 9pt;
    SCROLLBAR-HIGHLIGHT-COLOR: #ffffff;
    SCROLLBAR-SHADOW-COLOR: #f9f8f5;
    SCROLLBAR-3DLIGHT-COLOR: #B8E1F9;
    SCROLLBAR-ARROW-COLOR: #606d79;
    SCROLLBAR-TRACK-COLOR: #f9f8f5;
    FONT-FAMILY: "宋体";
    SCROLLBAR-DARKSHADOW-COLOR: #B8E1F9
}
   </style> 
</head>
<body style="background:#E7F5FD;">
    <form id="form1" runat="server">
        <table style="width: 100%; height: 100%; table-layout: fixed" border="0" cellpadding="0"
            cellspacing="0">
            <tr>
                <td valign="top">
                <div class="sdiv">

                    <asp:TreeView ID="TreeView1" runat="server" NodeIndent="10" Target="MainFrame"
                        Width="100%" Height="99%" ExpandDepth="0" AutoGenerateDataBindings="False" 
                        CollapseImageUrl="~/Images/treeMinus.gif" ExpandImageUrl="~/Images/treePlus.gif">
                        <ParentNodeStyle Font-Bold="False" />
                        <HoverNodeStyle BackColor="#C0E0FF" BorderColor="#003F98" BorderStyle="Solid" BorderWidth="1px"
                            Font-Underline="True" />
                        <SelectedNodeStyle BackColor="#C0E0FF" BorderColor="#003F98" BorderStyle="Solid"
                            BorderWidth="1px" Font-Underline="False" HorizontalPadding="1px" VerticalPadding="1px" />
                        <NodeStyle HorizontalPadding="5px" NodeSpacing="1px" VerticalPadding="1px" />
                    </asp:TreeView>
                 </div>
                </td>
            </tr>
        </table>
    </form>
</body>
</html>
